### ISSUE TITLE
web-applications scan results support

### ISSUE THREAD

**Issue by azhurbilo** [tenable/Security-Hub#9]
Do you plan support web scan results too (both new and legacy scan type)?

https://cloud.tenable.com/app.html#/dashboards/workbench/web-applications/plugin

**Comment by SteveMcGrath** [comment]
Web vulnerable are not included in the vulnerability export api, hence why they are not shown through this tool.  Down the road if the WAS APIs we’re expanded to support export of more than a single asset at a time, then it may be possible.

**Comment by FQRune** [comment]
Besides adding the ability to import web findings to AWS Security Hub, I think this issue should be extended to support import of any type of findings (web findings, network scans etc..) so Security Hub can be used as a centralized location vulnerability storage found within an organization.

Currently, this script is [only importing AWS related findings](https://github.com/tenable/Security-Hub/blob/master/sechubingest.py#L272) detected by Tenable through the AWS Connector. The very same thing can be accomplished much easier by using AWS Inspector instead of Tenable. As a bonus, AWS Inspector findings will automatically be pushed into Security Hub.

**Comment by RuneStone0** [comment]
Besides adding the ability to import web findings to AWS Security Hub, I think this issue should be extended to support import of any type of findings (web findings, network scans etc..) so Security Hub can be used as a centralized location vulnerability storage found within an organization.

Currently, this script is [only importing AWS related findings](https://github.com/tenable/Security-Hub/blob/master/sechubingest.py#L272) detected by Tenable through the AWS Connector. The very same thing can be accomplished much easier by using AWS Inspector instead of Tenable. As a bonus, AWS Inspector findings will automatically be pushed into Security Hub.

**Comment by SteveMcGrath** [comment]
Only importing AWS findings was by design.  WAS scanning right now would require the right APIs to pull the data in a scalable manner.
